[package]
name = "TAUDIO-WAA_NATIVE"
version = "0.0.28"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "taudio_waa_native"
crate-type = ["staticlib", "cdylib"]


[dependencies]
web-audio-api = "0.15.0"
rand = "0.8.4"